### ISSUE TITLE
Add --save path option

### ISSUE THREAD

**Issue by Psy-Fer** [Psy-Fer/CoVarPlot#3]
Add an option on where to save the file, as well as port some DPI and size control from SquigglePlot

**Comment by hoelzer** [comment]
I would be really interested in such a feature! I'm currently trying to integrate the script in our https://github.com/replikation/poreCov pipeline. To do so, I encapsulated the script and the dependencies in a Docker/Singularity container. Now, I have issues when running the script in a Singularity container w/ Nextflow :) 

Basically, it tries then to write the output to:

```
OSError: [Errno 30] Read-only file system: '/sampe123.CoVarPlot.png'
``` 

which fails due to permissions. I think a `--save` would solve that.

**Comment by Psy-Fer** [comment]
Okie dokie. I'll add this and a a few other QoL stuff in the next few days.

I enjoyed the pre-print for poreCov :)

**Comment by Psy-Fer** [comment]
This has been added in commit https://github.com/Psy-Fer/CoVarPlot/commit/8fd6b02f5ba5be923de0777cabaeeb21baff5bc0 

Added option `-s, --save` where a path is given to save the file said path.

If neither --show nor --save is given it throws an error
